name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install snapd
      run: |
        echo Install snapd
        sudo apt update
        sudo apt install snapd
    - name: Install Julia
      run: |
        echo Install Julia
        sudo snap install julia --classic
    - name: Install Dependency
      run: |
        julia -e 'using Pkg; 
        Pkg.add("https://github.com/devsisters/XLSXasJSON.jl"); 
        Pkg.add("https://github.com/yongheekim-dev/Nameless.jl");`
