on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Setting Variables
        id: vars
        shell: bash
        run: |
          echo "리비전을 파싱합니다..."
          GLOB_PATTERN="r[0-9][0-9][0-9][0-9]"
          echo "::set-output name=REV::$(git describe --match "$GLOB_PATTERN" --abbrev=0 --tags ${{ github.sha }})"
          echo "이번 리비전: $REV"
          NUM=${REV:2}
          NUM=$(expr $NUM - 1)
          NUM=$(printf "%04d\n" $NUM)
          echo "::set-output name=REV::$(r$NUM)"
          echo "이전 리비전: $NEW_REV"

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: false
