name: CoverageReport
on:
  push:
    branches:
      - master
    paths:
      - '**.info'

env:
  path_lcov: "test/coverage/lcov.info"
  path_report: "test/coverage"
  path_history: "test/coverage/history"

jobs:
  jobs_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: lcov
          path: ${{ env.path_lcov }}
  jobs_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "coverage-report"
      - uses: actions/download-artifact@v2
        with:
          name: lcov
          path: ${{ env.path_report }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.1
        with:
          reports: "${{ env.path_lcov }}"
          targetdir: "${{ env.path_report }}"
          reporttypes: "Badges;HtmlInline;TextSummary" # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
          historydir: "${{ env.path_history }}" # Optional directory for storing persistent coverage information. Can be used in future reports to show coverage evolution.
          assemblyfilters: "+*" # Optional list of assemblies that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
          classfilters: "+*" # Optional list of classes that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
          filefilters: "+*" # Optional list of files that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
          verbosity: "Info" # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
          tag: "${{ github.run_number }}" # Optional tag or build version.

      - name: CommitReport
        uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: "${{ env.path_report }}/*"
          message: "Coverage Report ${{ github.sha }}"
          ref: "coverage-report"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged


